// Build-time generator: parse data/loop_colors.xlsx into a static JS array of
// {code, name, hex}. Prepends the five core black/white cans that are missing
// from the source sheet. Emits src/colors.js — the app does NO runtime fetch.
import xlsx from 'xlsx';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const xlsxPath = fileURLToPath(new URL('../data/loop_colors.xlsx', import.meta.url));
const outPath = fileURLToPath(new URL('../public/colors.js', import.meta.url));

// Core black/white cans absent from the sheet — added manually at the top.
const MANUAL = [
  { code: 'LP-100', name: 'WHITE', hex: '#f7f7f2' },
  { code: 'LP-101', name: 'GLOSS WHITE', hex: '#ffffff' },
  { code: 'LP-103', name: 'BLACK MATT', hex: '#141414' },
  { code: 'LP-104', name: 'BLACK', hex: '#0a0a0a' },
  { code: 'LP-105', name: 'BLACK GLOSS', hex: '#000000' },
];

const normHex = (h) => {
  let s = String(h).trim();
  if (!s.startsWith('#')) s = '#' + s;
  return s.toLowerCase();
};

const wb = xlsx.readFile(xlsxPath);
const ws = wb.Sheets[wb.SheetNames[0]];
const rows = xlsx.utils.sheet_to_json(ws, { defval: '' });

const fromSheet = rows.map((r) => ({
  code: String(r['Product Code']).trim(),
  name: String(r['Color Name']).trim(),
  hex: normHex(r['HEX']),
})).filter((c) => c.code && c.name && c.hex);

const colors = [...MANUAL, ...fromSheet];

// ---- Validation ----
const errors = [];
const hexRe = /^#[0-9a-f]{6}$/;
const seenCodes = new Set();
for (const c of colors) {
  if (!hexRe.test(c.hex)) errors.push(`Bad hex for ${c.code}: ${c.hex}`);
  if (!/^LP-/.test(c.code)) errors.push(`Bad code format: ${c.code}`);
  if (seenCodes.has(c.code)) errors.push(`Duplicate code: ${c.code}`);
  seenCodes.add(c.code);
}
if (colors.length !== 216) {
  errors.push(`Expected 216 colours, got ${colors.length} (sheet: ${fromSheet.length} + manual: ${MANUAL.length})`);
}
// LP-450 (DOLLY NOIRE / Metallized Black) must survive — retailers list it as
// Metallized Black; we keep the sheet's name and do NOT dedupe it away.
if (!colors.some((c) => c.code === 'LP-450')) {
  errors.push('LP-450 (DOLLY NOIRE) missing — must not be deduped away');
}
if (errors.length) {
  console.error('VALIDATION FAILED:\n' + errors.join('\n'));
  process.exit(1);
}

const banner = `// AUTO-GENERATED by scripts/build-colors.mjs — do not edit by hand.\n`
  + `// Source: loop_colors.xlsx from github.com/stuartcarroll/SprayPaintSwatches\n`
  + `// plus 5 manually-added core black/white cans. ${colors.length} colours total.\n`;
const body = `export const COLORS = ${JSON.stringify(colors, null, 0)};\n`;
writeFileSync(outPath, banner + body);

console.log(`Wrote ${colors.length} colours to public/colors.js`);
console.log(`  manual: ${MANUAL.length}, from sheet: ${fromSheet.length}`);
console.log(`  first: ${colors[0].code} ${colors[0].name} ${colors[0].hex}`);
console.log(`  last:  ${colors.at(-1).code} ${colors.at(-1).name} ${colors.at(-1).hex}`);
